#!/bin/bash

echo "🚀 Email RAG Assistant - Environment Setup Helper"
echo "================================================"
echo ""
echo "This script will help you set up environment variables for Vercel deployment."
echo ""

# Function to generate random string
generate_secret() {
    openssl rand -base64 32 | tr -d "=+/" | cut -c1-32
}

echo "📝 Required Environment Variables:"
echo ""
echo "1. OPENAI_API_KEY"
echo "   Get from: https://platform.openai.com/api-keys"
echo ""
echo "2. PINECONE_API_KEY"
echo "   Get from: https://console.pinecone.io/"
echo ""
echo "3. PINECONE_ENVIRONMENT"
echo "   Example: us-east-1, us-west-1, etc."
echo ""
echo "4. PINECONE_INDEX_NAME"
echo "   Recommended: email-embeddings"
echo ""
echo "5. JWT_SECRET"
echo "   Generated: $(generate_secret)"
echo ""
echo "6. NEXTAUTH_SECRET"
echo "   Generated: $(generate_secret)"
echo ""
echo "================================================"
echo ""
echo "📋 Quick Copy for Vercel Dashboard:"
echo ""
echo "OPENAI_API_KEY=your_openai_api_key_here"
echo "PINECONE_API_KEY=your_pinecone_api_key_here"
echo "PINECONE_ENVIRONMENT=us-east-1"
echo "PINECONE_INDEX_NAME=email-embeddings"
echo "JWT_SECRET=$(generate_secret)"
echo "NEXTAUTH_SECRET=$(generate_secret)"
echo ""
echo "================================================"
echo ""
echo "🔗 Add these at: https://vercel.com/seanwmeehan-gmailcoms-projects/emailogan-web/settings/environment-variables"
echo ""
echo "After adding environment variables, redeploy with:"
echo "  vercel --prod"
echo ""